# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.erp: '%env(ERP_TYPE)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\EventListener\LoginResponseListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }

    App\EventListener\AuthenticationFailureListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailure }

    App\Erp\Core\ErpManager:
        autowire: true
        arguments:
            $httpClient: '@http_client'

    App\Cron\Core\GetUsers:
        autowire: true
        arguments:
            $repository: '@App\Repository\UserRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetProducts:
        autowire: true
        arguments:
            $categoryRepository: '@App\Repository\CategoryRepository'
            $productRepository: '@App\Repository\ProductRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetCategories:
        autowire: true
        arguments:
            $categoryRepository: '@App\Repository\CategoryRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetPriceList:
        autowire: true
        arguments:
            $priceListRepository: '@App\Repository\PriceListRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetPriceListDetailed:
        autowire: true
        arguments:
            $productRepository: '@App\Repository\ProductRepository'
            $priceListRepository: '@App\Repository\PriceListRepository'
            $priceListDetailedRepository: '@App\Repository\PriceListDetailedRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetPriceListUser:
        autowire: true
        arguments:
            $userRepository: '@App\Repository\UserRepository'
            $priceListRepository: '@App\Repository\PriceListRepository'
            $priceListUserRepository: '@App\Repository\PriceListUserRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetStocks:
        autowire: true
        arguments:
            $productRepository: '@App\Repository\ProductRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetMainAttributes:
        autowire: true
        arguments:
            $attributeMainRepository: '@App\Repository\AttributeMainRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetSubAttributes:
        autowire: true
        arguments:
            $attributeSubRepository: '@App\Repository\AttributeSubRepository'
            $productRepository: '@App\Repository\ProductRepository'
            $attributeMainRepository: '@App\Repository\AttributeMainRepository'
            $productAttributeRepository: '@App\Repository\ProductAttributeRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetMigvans:
        autowire: true
        arguments:
            $migvanRepository: '@App\Repository\MigvanRepository'
            $userRepository: '@App\Repository\UserRepository'
            $productRepository: '@App\Repository\ProductRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetPacks:
        autowire: true
        arguments:
            $packMainRepository: '@App\Repository\PackMainRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Cron\Core\GetProductPacks:
        autowire: true
        arguments:
            $packMainRepository: '@App\Repository\PackMainRepository'
            $productPackRepository: '@App\Repository\ProductPackRepository'
            $productRepository: '@App\Repository\ProductRepository'
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Service\PriceChecker:
        autowire: true
        arguments:
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Service\StockChecker:
        autowire: true
        arguments:
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Service\MigvanChecker:
        autowire: true
        arguments:
            $erpManager: '@App\Erp\Core\ErpManager'

    App\Service\OneSignal:
        autowire: true
        arguments:
            $httpClient: '@http_client'
            $userRepository: '@App\Repository\UserRepository'

