version: '3'

networks:
  nginx-php81-mysql8-node:

services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    ports:
      - "8085:80"
    volumes:
      - ./backend:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - mysql8-service
      - phpmyadmin-service
    networks:
      - nginx-php81-mysql8-node

  # php
  php81-service:
    image: spetsar/backend-template
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/project
    networks:
      - nginx-php81-mysql8-node
    depends_on:
      mysql8-service:
        condition: service_healthy

  # mysql
  mysql8-service:
    image: mysql:8
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      - nginx-php81-mysql8-node
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  # phpMyAdmin
  phpmyadmin-service:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql8-service
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - nginx-php81-mysql8-node

  front:
    image: spetsar/front-template
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - nginx-php81-mysql8-node