<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '90459d5cc76b79a85bb30a81236feefa',
  'DATABASE_URL' => 'mysql://root:secret@mysql8-service:3306/app?serverVersion=15&charset=utf8',
  'CORS_ALLOW_ORIGIN' => '^.*$',
  'JWT_SECRET_KEY' => '%kernel.project_dir%/config/jwt/private.pem',
  'JWT_PUBLIC_KEY' => '%kernel.project_dir%/config/jwt/public.pem',
  'JWT_PASSPHRASE' => '701ac75f16f09b77dc7745f8c1ffb1823c1eb85e1ccd8c4f0dd51736e58dbdc3',
  'VPS_1_SERVER' => '3.68.115.205',
  'VPS_1_USERNAME' => 'july',
  'VPS_1_PASSWORD' => 'lE1wE2sP5i',
  'VPS_1_FOLDER' => 'digitrade.com.ua',
  'VPS_1_OUTPUT_FOLDER' => 'output',
  'DOMAIN_IMAGE' => 'https://foodappeal-b2b.com/src/img/',
  'NOTIFICATION_IDENTIFIER' => 'ceremonitea',
  'ERP_TYPE' => 'Priority',
  'ERP_USERNAME' => 'digitrade',
  'ERP_PASSWORD' => 'DIgi3251',
  'ERP_URL' => 'https://www.eshbelsaas.co.il/pr17/odata/Priority/tabzf97f.ini/a230820',
  'IS_MUST_DELIVERY_PRICE' => 'true',
  'MINIMUM_DELIVERY_PRICE' => '250',
  'IS_MAX_ORDER_DISCOUNT' => 'true',
  'MAX_PRICE_FOR_DISCOUNT' => '750',
  'DISCOUNT_PRECENT_FOR_MAX_PRICE' => '7',
  'IS_USED_MIGVAN' => 'true',
  'IS_USED_STOCK' => 'false',
  'FLASHY' => 'pwccyaasb88qpf51004a8rhmytcy0ics',
  'ONESIGNAL_APP_ID' => 'd904db7c-1563-432a-9b9d-0e964bb4cc4a',
  'ONESIGNAL_API_KEY' => 'YzlhMDM2YjctNjNmMi00Nzk3LTkyYmItNDhhYjI1NjVjNTNk',
);
